// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"database/sql"
)

type Chargebox struct {
	Chargeboxid             string         `json:"chargeboxid"`
	EndpointAddress         sql.NullString `json:"endpoint_address"`
	Ocppprotocol            sql.NullString `json:"ocppprotocol"`
	Chargepointvendor       sql.NullString `json:"chargepointvendor"`
	Chargepointmodel        sql.NullString `json:"chargepointmodel"`
	Chargepointserialnumber sql.NullString `json:"chargepointserialnumber"`
	Chargeboxserialnumber   sql.NullString `json:"chargeboxserialnumber"`
	Fwversion               sql.NullString `json:"fwversion"`
	Fwupdatestatus          sql.NullString `json:"fwupdatestatus"`
	Fwupdatetimestamp       sql.NullTime   `json:"fwupdatetimestamp"`
	Iccid                   sql.NullString `json:"iccid"`
	Imsi                    sql.NullString `json:"imsi"`
	Metertype               sql.NullString `json:"metertype"`
	Meterserialnumber       sql.NullString `json:"meterserialnumber"`
	Diagnosticsstatus       sql.NullString `json:"diagnosticsstatus"`
	Diagnosticstimestamp    sql.NullTime   `json:"diagnosticstimestamp"`
	Lastheartbeattimestamp  sql.NullTime   `json:"lastheartbeattimestamp"`
	Note                    sql.NullString `json:"note"`
}
